apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-document-backend
  namespace: ai-document-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-document-backend
  template:
    metadata:
      labels:
        app: ai-document-backend
    spec:
      containers:
      - name: backend
        image: YOUR_ECR_URI/ai-document-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgresql://user:pass@postgres-service:5432/mydb"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ai-document-backend-service
  namespace: ai-document-assistant
spec:
  selector:
    app: ai-document-backend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 